global.objControlId = id;
global.gamepad_id = -1;
has_control = true;
control_mode = "keyboard";
scrGamepad();
pad_left = false;
pad_right = false;
pad_up = false;
pad_down = false;
button_jump = false;
button_shoot = false;
button_pause = false;